@echo off

set CSDTKMAKEDIR=make64
set CSDTKVER=4
set CSDTKVERSION=4.2
set CSDTK4INSTALLDIR=%~dp0
set PATH=%CSDTK4INSTALLDIR%%CSDTKMAKEDIR%;%CSDTK4INSTALLDIR%perl\bin;%CSDTK4INSTALLDIR%python27;%CSDTK4INSTALLDIR%mips-elf-4.4.2\bin;%CSDTK4INSTALLDIR%nanopb-0.3.9;%PATH%

